=head1 NAME

gcis-sync : synchronize data in the GCIS with various sources, such as dx.doi.org, CEOS, PO.DAAC.

=for HTML <a href="http://travis-ci.org/USGCRP/gcis-sync"><img src="https://secure.travis-ci.org/USGCRP/gcis-sync.png" alt="Build status" /></a>

=head1 DESCRIPTION

sync.pl pulls data from a variety of sources, and ingests the data into the L<GCIS|http://data.globalchange.gov>.

The mechanism for pulling from the various sources varies, and is described in the documentation for a particular "syncer".

Please see L<sync.pl|https://github.com/USGCRP/gcis-sync/blob/master/sync.pl> for usage of the command line synchronization utility.

For the details of a particular syncer, see the pod for that syncer.  For instance :
L<lib/Gcis/syncer/ceos|https://github.com/USGCRP/gcis-sync/blob/master/lib/Gcis/syncer/ceos.pod>,
L<lib/Gcis/syncer/podaac|https://github.com/USGCRP/gcis-sync/blob/master/lib/Gcis/syncer/podaac.pod>.

=head1 INSTALLATION and USAGE

 git clone https://github.com/USGCRP/gcis-sync
 cd gcis-sync
 cpanm --installdeps .
 ./sync.pl --help

=cut


