#!/bin/bash -ex

url=${1:-http://localhost:3000}

echo $url
cd `dirname $0`
cd ..

./sync.pl --url=$url --syncers=yaml   --gcid='/platform/.*' --log_level=debug
./sync.pl --url=$url --syncers=podaac --gcid='/dataset/nasa-podaac.*tp.j1.ostm.*' --log_level=debug
./sync.pl --url=$url --syncers=yaml   --gcid='/dataset/nasa-podaac-.*'  --log_level=debug

